version: "3"

services:
  app:
    build: $PWD/app
    volumes:
      - $PWD/app:/app
    ports:
      - "3000:3000"
      - "35729:35729"
  api:
    build: $PWD/api
    volumes:
      - $PWD/api:/app
    ports:
      - "4000:4000"
    environment:
      RAILS_ENV: development
