version: "3"

services:
  web:
    build: ./app
    command: bash -c "yarn start"
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - api
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    restart: always
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
