version: "3"

services:
  web:
    build: ./app
    command: bash -c "yarn start"
    restart: always
    volumes:
      - ./app/src:/app/src
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      # For Linux users, use http://localhost:4000/chess instead.
      - REACT_APP_API=http://192.168.99.100:4000/chess
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    restart: always
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
