version: "3"

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
    environment:
      RAILS_ENV: development
